/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

//@ts-nocheck
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps, useFrame } from "@react-three/fiber";
import type { Mesh } from "three";

export function Model(props: GroupProps) {
  const { nodes, materials } = useGLTF("/logo2020.glb");

  const logoMesh = useRef<Mesh>()
  useFrame(({clock}) => {
    const a = clock.getElapsedTime()
    logoMesh.current.position.y = Math.sin(a)
  })

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        ref={logoMesh}
        geometry={nodes.Logo2020.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, Math.PI/8]}
      />
    </group>
  );
}

// useGLTF.preload("/logo2020.glb");
